version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quarkus-postgres
    environment:
      POSTGRES_DB: quarkusdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quarkusdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Opcional: Administrador de base de datos
  adminer:
    image: adminer:latest
    container_name: quarkus-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: